Check manually for Rcmdr 1.9-3
R does not check version of packages in Imports when loading them
(see "Writing R extensions"), even tough it will update such packages
when installing a new package that requires a newer version. This means
that users can have Rcmdr 1.9-2 installed, which will generate the
following error when loading RcmdrPlugin.temis:
Error : .onAttach failed in attachNamespace() for 'RcmdrPlugin.temis', details:
  call: path.package(...)
  error: none of the packages are loaded
Error: package/namespace load failed for 'RcmdrPlugin.temis'

Better do the check manually and print a more explicit error message,
even if the situation is going to be rare (manually installed packages
only).

git-svn-id: svn://svn.r-forge.r-project.org/svnroot/r-temis@377 edb9625f-4e0d-4859-8d74-9fd3b1da38cb